import simpleGit from "simple-git";
import { popFromBuildQueue } from "../services/queue.service.js";
import connectDB from "../config/db.js";
import Project from "../models/project.js";
import Deployment from "../models/deployment.model.js";
import fs from "fs/promises";
import path from "path";
import { autoGenerateDockerfile, buildDockerImage } from "../services/docker.service.js";
import { pushImageToEcr } from "../services/ecr.service.js";
import {
    registerECSTaskDefinition,
    runECSTask,
    ensureECSService,
    describeECSService,
    ecsServiceName,
} from "../services/ecs.service.js";
import {
    CONTAINER_PORT,
    ensureTargetGroup,
    ensureListenerRule,
    getTargetHealth,
    hostForProject,
    buildLiveUrl,
} from "../services/alb.service.js";
import config from "../config/config.js";
import { createLogger } from "../services/log.service.js";

const git = simpleGit()

const STALE_AFTER_MS = 15 * 60 * 1000

/*
  How long to wait for a freshly deployed container to pass ALB health checks.
  Generous: the task has to be placed, pull its image from ECR, boot, and then
  pass two checks 15s apart. Comfortably inside the 15-minute watchdog window.
*/
const HEALTH_POLL_INTERVAL_MS = 10 * 1000
const HEALTH_TIMEOUT_MS = 3 * 60 * 1000


async function cleanStaleBuilds() {
    const cutoff = new Date(Date.now() - STALE_AFTER_MS)

    const result = await Project.updateMany(
        {
            status: { $in: ["BUILDING", "DEPLOYING"] },
            updatedAt: { $lt: cutoff }
        },
        { status: "FAILED" }
    )
    if (result.modifiedCount > 0) console.log(`[Watchdog] Cleaned up ${result.modifiedCount} zombie build(s) stuck in BUILDING`)

    // Deployments must be cleaned too, otherwise the UI shows a spinner forever
    // on a build whose worker died.
    const deploymentResult = await Deployment.updateMany(
        {
            status: { $in: ["QUEUED", "BUILDING", "DEPLOYING"] },
            updatedAt: { $lt: cutoff }
        },
        {
            status: "FAILED",
            errorMessage: "Build timed out or the worker stopped unexpectedly.",
            finishedAt: new Date()
        }
    )
    if (deploymentResult.modifiedCount > 0) {
        console.log(`[Watchdog] Cleaned up ${deploymentResult.modifiedCount} zombie deployment(s)`)
    }
}


async function startWorker() {
    await connectDB()
    console.log("Build Worker started and waiting for tasks...")

    await cleanStaleBuilds()

    setInterval(cleanStaleBuilds, STALE_AFTER_MS)

    while (true) {
        try {
            const job = await popFromBuildQueue()
            if (job) await processBuildJob(job)
        } catch (error) {
            console.error("[Worker] Fatal error in worker loop:", error.message)
            await new Promise((resolve) => setTimeout(resolve, 3000))
        }
    }
}



/**
 * Block until the ALB will actually route traffic to the new container.
 *
 * "ECS started the task" and "the app is reachable" are different claims, and
 * only the second one justifies READY. A container that boots but never answers
 * on its port looks completely healthy from ECS's side while the ALB serves 503,
 * so target health is the real signal.
 *
 * Throws with a diagnosable message rather than leaving the build to spin.
 */
async function waitForRoutableService({ serviceName, targetGroupArn, logger }) {
    const deadline = Date.now() + HEALTH_TIMEOUT_MS
    let lastSummary = null

    while (Date.now() < deadline) {
        const [service, health] = await Promise.all([
            describeECSService(serviceName),
            getTargetHealth(targetGroupArn),
        ])

        if (health.healthy > 0) {
            logger.log(
                `Health checks passed (${health.healthy}/${health.total} target${health.total === 1 ? "" : "s"} healthy).`,
                "system"
            )
            return
        }

        /*
          The deployment circuit breaker has already given up and rolled back, so
          waiting out the remaining timeout would tell us nothing new.
        */
        if (service?.rolloutState === "FAILED") {
            for (const event of service.events) logger.log(`ECS: ${event}`, "stderr")
            throw new Error(
                service.rolloutStateReason ||
                "ECS rolled back the deployment — the new container failed to start."
            )
        }

        // Only log on change: at a 10s cadence, repeating an identical line would
        // bury the interesting output.
        const targetState = health.states.length
            ? `target ${health.states.join(", ")}`
            : "no targets registered yet"
        const summary = `${service?.runningCount ?? 0}/${service?.desiredCount ?? 0} task(s) running, ${targetState}`

        if (summary !== lastSummary) {
            logger.log(`Waiting for health checks — ${summary}`, "system")
            lastSummary = summary
        }

        await new Promise((resolve) => setTimeout(resolve, HEALTH_POLL_INTERVAL_MS))
    }

    /*
      Timed out. The health-check description and the ECS event stream are the
      only places that say *why*, so both are surfaced — otherwise the user just
      sees a failure with no cause.
    */
    const [service, health] = await Promise.all([
        describeECSService(serviceName).catch(() => null),
        getTargetHealth(targetGroupArn).catch(() => null),
    ])

    for (const event of service?.events || []) logger.log(`ECS: ${event}`, "stderr")

    const reason = health?.reasons?.length ? health.reasons.join("; ") : "no response from the container"

    throw new Error(
        `App did not pass health checks within ${HEALTH_TIMEOUT_MS / 60000} minutes (${reason}). ` +
        `Make sure it listens on port ${CONTAINER_PORT} and returns 2xx/3xx on "/".`
    )
}

/**
 * Provision per-project routing and start (or roll) the ECS service.
 *
 * Target group and rule are recorded on the project *before* waiting for health,
 * so a timeout still leaves enough state behind for deletion to clean up.
 *
 * @returns {string} the project's live URL
 */
async function deployBehindLoadBalancer({ project_id, taskDefArn, logger }) {
    // The subdomain comes from project.name, which the schema already constrains
    // to lowercase [a-z0-9-] — exactly a valid DNS label.
    const project = await Project.findById(project_id).select("name")
    if (!project) throw new Error("Project was deleted while its build was running.")

    const host = hostForProject(project.name)
    logger.log(`Provisioning routing for ${host}`, "system")

    const targetGroupArn = await ensureTargetGroup(project_id, project.name)
    const albListenerRuleArn = await ensureListenerRule(targetGroupArn, host)
    const serviceName = ecsServiceName(project_id, project.name)

    const { created } = await ensureECSService({
        projectId: project_id,
        projectName: project.name,
        taskDefinitionArn: taskDefArn,
        targetGroupArn,
    })

    await Project.findByIdAndUpdate(project_id, {
        albTargetGroupArn: targetGroupArn,
        albListenerRuleArn,
        ecsServiceArn: serviceName,
    })

    logger.log(
        created
            ? "ECS service created — waiting for the container to become healthy..."
            : "Rolling update started — the previous version keeps serving until the new one is healthy...",
        "system"
    )

    await waitForRoutableService({ serviceName, targetGroupArn, logger })

    return buildLiveUrl(project.name)
}


async function processBuildJob(job) {
    const { project_id, deploymentId, repoUrl, branch } = job
    const workspaceDir = path.resolve(process.cwd(), "workspace", project_id)

    // Older queue entries (enqueued before deployments existed) have no
    // deploymentId. Fail loudly rather than crashing the worker loop.
    if (!deploymentId) {
        console.error(`[Worker] Job for project ${project_id} has no deploymentId — skipping`)
        await Project.findByIdAndUpdate(project_id, { status: "FAILED" })
        return
    }

    const logger = createLogger({ projectId: project_id, deploymentId })

    // Tracks which step to mark failed if an exception is thrown.
    let currentStep = "CLONE"
    const onLog = (chunk, stream) => logger.log(chunk, stream)

    try {
        console.log(`\n[Worker] Picked up job for project ${project_id} (deployment ${deploymentId})`)
        await logger.status("BUILDING")


        currentStep = "CLONE"
        await logger.step("CLONE", "running")
        await fs.rm(workspaceDir, { recursive: true, force: true })
        await fs.mkdir(workspaceDir, { recursive: true })
        logger.log(`Cloning ${repoUrl} (branch: ${branch})`, "system")
        await git.clone(repoUrl, workspaceDir, ["--branch", branch, "--depth", "1"])
        logger.log("Repository cloned successfully.", "system")
        await logger.step("CLONE", "success")


        currentStep = "DOCKERFILE"
        await logger.step("DOCKERFILE", "running")
        await autoGenerateDockerfile(workspaceDir, onLog)
        await logger.step("DOCKERFILE", "success")


        currentStep = "BUILD"
        await logger.step("BUILD", "running")
        logger.log("Building Docker image...", "system")
        const imageTag = await buildDockerImage(project_id, workspaceDir, onLog)
        logger.log(`Docker image ready: ${imageTag}`, "system")
        await logger.step("BUILD", "success")


        currentStep = "PUSH"
        await logger.step("PUSH", "running")
        const ecrRepoName = `launchbase-${project_id.toLowerCase()}`
        const ecrImageUri = await pushImageToEcr(imageTag, ecrRepoName, "latest", onLog)
        await logger.step("PUSH", "success")


        currentStep = "DEPLOY"
        await logger.step("DEPLOY", "running")
        await logger.status("DEPLOYING", { ecrImageUri })
        logger.log("Registering ECS task definition...", "system")
        const taskDefArn = await registerECSTaskDefinition(project_id, ecrImageUri)

        /*
          Two deploy paths.

          With an ALB configured, the container runs under an ECS *service*: it
          is supervised, restarted if it dies, replaced without downtime on
          redeploy, and reachable at a stable subdomain.

          Without one there is nothing to route to, so a bare one-shot task is
          launched and liveUrl stays null — the UI renders that as "URL pending".
          An ALB bills ~$16/month whether or not it is used, so running without
          one has to remain a first-class path, not a broken one.
        */
        let liveUrl = null

        if (config.ALB_ENABLED) {
            liveUrl = await deployBehindLoadBalancer({ project_id, taskDefArn, logger })
            logger.log(`Live at ${liveUrl}`, "system")
            await logger.step("DEPLOY", "success")

            // Logged before the terminal status: status() flushes pending lines and
            // clients refetch on READY, so anything emitted after it could be missed.
            logger.log("Deployment complete.", "system")
            await logger.status("READY", { liveUrl, ecrImageUri })
        } else {
            logger.log("Spinning up serverless Fargate container...", "system")
            const taskArn = await runECSTask(taskDefArn)
            logger.log(`Serverless task starting: ${taskArn}`, "system")
            logger.log("No load balancer configured — the app has no public URL yet.", "system")
            await logger.step("DEPLOY", "success")

            logger.log("Deployment complete.", "system")
            await logger.status("READY", { taskArn, ecrImageUri })
        }

    } catch (error) {
        console.error(`[Worker] Build failed for project ${project_id}:`, error.message)
        logger.log(`Build failed during ${currentStep}: ${error.message}`, "stderr")
        await logger.step(currentStep, "failed")
        await logger.status("FAILED", { errorMessage: error.message })
    }
    finally {
        // Guarantee the tail of the log reaches Mongo before the job ends.
        await logger.flush()
        console.log(`[Worker] Cleaning up workspace for project ${project_id}`)
        await fs.rm(workspaceDir, { recursive: true, force: true })
    }
}


startWorker()
