import simpleGit from "simple-git";
import { popFromBuildQueue } from "../services/queue.service.js";
import connectDB from "../config/db.js";
import Project from "../models/project.js";
import fs from "fs/promises";
import path from "path";
import { autoGenerateDockerfile, buildDockerImage } from "../services/docker.service.js";
import { pushImageToEcr } from "../services/ecr.service.js";

const git = simpleGit()


async function cleanStaleBuilds() {
    const fifteenMinutesAgo = new Date(Date.now() - 15 * 60 * 1000)
    const result = await Project.updateMany(
        {
            status: "BUILDING",
            updatedAt: { $lt: fifteenMinutesAgo }
        },
        { status: "FAILED" }
    )
    if(result.modifiedCount>0) console.log(`[Watchdog] Cleaned up ${result.modifiedCount} zombie build(s) stuck in BUILDING`)
}


async function startWorker() {
    await connectDB()
    console.log("Build Worker started and waiting for tasks...")

    await cleanStaleBuilds()

    setInterval(cleanStaleBuilds,15*60*1000)

    while (true) {
        try {
            const job = await popFromBuildQueue()
            if (job) await processBuildJob(job)
        } catch (error) {
            console.error("[Worker] Fatal error in worker loop:", error.message)
            await new Promise((resolve) => setTimeout(resolve, 3000))
        }
    }
}



async function processBuildJob(job) {
    const { project_id, repoUrl, branch } = job
    const workspaceDir = path.resolve(process.cwd(), "workspace", project_id)
    try {
        console.log(`\n[Worker] Picked up job for project ${project_id}`)


        await Project.findByIdAndUpdate(project_id, { status: "BUILDING" })
        console.log(`[Worker] Status updated to Building`)


        await fs.rm(workspaceDir, { recursive: true, force: true })
        await fs.mkdir(workspaceDir, { recursive: true })


        console.log(`[Worker] Cloning ${repoUrl} (branch:${branch}) into ${workspaceDir}`)
        await git.clone(repoUrl, workspaceDir, ["--branch", branch, "--depth", "1"])
        console.log(`[Worker] Succesfully cloned project ${project_id}! Ready for Docker (Phase 3).`)


        console.log(`[Worker] Generating Dockerfile if not present...`)
        await autoGenerateDockerfile(workspaceDir)
        console.log(`[Worker] Dockerfile prepared for project ${project_id}!`)


        console.log(`[Worker] Building Docker image for project ${project_id}`)
        const imageTag = await buildDockerImage(project_id, workspaceDir)
        console.log(`[Worker] Docker image Ready: ${imageTag}`)


        console.log(`[Worker] Pushing Docker image to AWS ECR...`)
        const ecrRepoName = `launchbase-${project_id.toLowerCase()}`
        const ecrImageUri = await pushImageToEcr(imageTag, ecrRepoName)
        console.log(`[Worker] Successfully pushed image to ECR: ${ecrImageUri}`)

    } catch (error) {
        console.error(`[Worker] Build/Clone failed for project ${project_id}`, error.message)
        await Project.findByIdAndUpdate(project_id, { status: "FAILED" })
    }
    //Uncomment it at the end of phase 3
    // finally{
    //     console.log(`[Worker] Cleaning up workspace for project ${project_id}`)
    //     await fs.rm(workspaceDir,{recursive:true,force:true})
    // }
}






startWorker()