import fs from 'fs/promises'
import path from 'path'
import { spawn } from 'child_process'


async function fileExists(filePath) {
    try {
        await fs.access(filePath)
        return true
    } catch (error) {
        return false
    }
}


async function detectPythonEntryPoint(workspaceDir) {
    try {
        const files = await fs.readdir(workspaceDir)
        const pythonFiles = files.filter((e) => {
            return e.endsWith(".py")
        })

        if (pythonFiles.length === 1) {
            console.log(`[Docker Service] Found single python file :${pythonFiles[0]}`)
            return pythonFiles[0];
        }

        for (const file of pythonFiles) {
            const filePath = path.join(workspaceDir, file)
            const content = await fs.readFile(filePath, "utf-8")

            const hasMainBlock = content.includes('if __name__ == "__main__":') || content.includes("if __name__ == '__main__':")
            const hasServerRun = content.includes(".run(") || content.includes("uvicorn") || content.includes("Flask(__name__)") || content.includes("FastAPI()");
            if (hasMainBlock || hasServerRun) {
                console.log(`[Docker service] Detected entry signature in ${file}`)
                return file
            }
        }

    } catch (error) {
        console.warn("[Docker Service] Error scanning directory for Python files:", error)
    }
    return "main.py"
}


async function autoGenerateDockerfile(workspaceDir) {
    const dockerfilePath = path.join(workspaceDir, "Dockerfile")
    if (await fileExists(dockerfilePath)) {
        console.log("[Docker Service] Custom Dockerfile found. Proceeding without overwriting")
        return
    }


    const packageJsonPath = path.join(workspaceDir, "package.json")
    if (await fileExists(packageJsonPath)) {
        console.log("[Docker Service] Node.js project detected (package.json found).")

        const packageContent = await fs.readFile(packageJsonPath, "utf-8")
        const packageData = JSON.parse(packageContent)

        const hasBuildScript = Boolean(packageData.scripts?.build)
        if (hasBuildScript) console.log("[Docker Service] Build script detected in package.json.")

        const hasStartScript=Boolean(packageData.scripts?.start)
        const mainFile=packageData.main || "index.js"
        const startCommand=hasStartScript?'CMD ["npm","start"]':`CMD ["node","${mainFile}"]`

        const nodeDockerfile = [
            "FROM node:18-alpine",
            "WORKDIR /app",
            "COPY package*.json ./",
            "RUN npm install",
            "COPY . .",
            hasBuildScript ? "RUN npm run build" : null,
            "RUN npm prune --production",
            "ENV PORT=8080",
            "EXPOSE 8080",
            startCommand,
        ]
            .filter(Boolean)
            .join("\n")

        await fs.writeFile(dockerfilePath, nodeDockerfile, "utf-8")
        console.log("[Docker Service] Successfully generated Node.js Dockerfile.")
        return
    }


    const requirementsTxtPath = path.join(workspaceDir, "requirements.txt")
    if (await fileExists(requirementsTxtPath)) {
        console.log("[Docker Service] Python project detected (requirements.txt found).")
        const entryFile = await detectPythonEntryPoint(workspaceDir)
        console.log(`[Docker Service] Target Python entry point: ${entryFile}`)
        const runCommand = entryFile === "manage.py" ? 'CMD ["python", "manage.py", "runserver", "0.0.0.0:8080"]' : `CMD ["python", "${entryFile}"]`;
        const pythonDockerfile = [
            "FROM python:3.12-slim",
            "WORKDIR /app",
            "COPY requirements.txt ./",
            "RUN pip install --no-cache-dir -r requirements.txt",
            "COPY . .",
            "ENV PORT=8080",
            "EXPOSE 8080",
            runCommand,
        ].join("\n")

        await fs.writeFile(dockerfilePath, pythonDockerfile, "utf-8")
        console.log("[Docker Service] Successfully generated Python Dockerfile.")
        return
    }


    const goModPath = path.join(workspaceDir, "go.mod")
    if (await fileExists(goModPath)) {
        console.log("[Docker Service] Go project detected (go.mod found).")
        const goDockerFile = [
            "FROM golang:1.20-alpine AS builder",
            "WORKDIR /app",
            "COPY go.mod go.sum* ./",
            "RUN go mod download",
            "COPY . .",
            "RUN CGO_ENABLED=0 go build -o main .",
            "",
            "FROM alpine:latest",
            "WORKDIR /app",
            "COPY --from=builder /app/main .",
            "ENV PORT=8080",
            "EXPOSE 8080",
            'CMD ["./main"]',
        ].join("\n")

        await fs.writeFile(dockerfilePath, goDockerFile, "utf-8")
        console.log("[Docker Service] Successfully generated Go DockerFile.")
        return
    }



    throw new Error(
        `[Docker Service] No recognized language configuration (package.json, requirements.txt, go.mod) or Dockerfile found in "${workspaceDir}". Cannot generate Dockerfile`
    )
}


function buildDockerImage(project_id,workspaceDir){
    return new Promise ((resolve,reject)=>{
        const imageTag=`launchbase-${project_id.toLowerCase()}:latest`
        const child=spawn("docker",["build","-t",imageTag,workspaceDir],{timeout:600000})

        child.stdout.on("data",(data)=>{
            console.log(`[Docker Build] ${data.toString().trim()}`)
        })

        child.stderr.on("data",(data)=>{
            console.warn(`[Docker Build] ${data.toString().trim()}`)
        })

        child.on("close",(code)=>{
            if(code==0){
                console.log(`[Docker Service] Successfully build and tagged image:${imageTag}`)
                resolve(imageTag)
            }
            else{
                const errorMsg=`[Docker Service] Docker Build failed with exit code ${code}`
                console.error(errorMsg)
                reject(new Error(errorMsg))
            }
        })

        child.on("error",(error)=>{
            console.error("[Docker Service] Failed to spawn docker command:",error.message)
            reject(error)
        })
    })
}


export{
    autoGenerateDockerfile,
    buildDockerImage
}